GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE0LCJuYW1lIjp7ImlkIjoxNCwibmFtZSI6IlJhbmRpIEEiLCJ1c2VybmFtZSI6InJhbmRpaHVnYTA1IiwicGFzc3dvcmQiOiI2MTMyNjExN2VkNGE5ZGRmM2Y3NTRlNzFlMTE5ZTViMyIsInJlZnJlc2hfdG9rZW4iOiJleUpoYkdjaU9pSklVekkxTmlJc0luUjVjQ0k2SWtwWFZDSjkuZXlKMWMyVnlTV1FpT2pFMExDSnVZVzFsSWpwN0ltbGtJam94TkN3aWJtRnRaU0k2SWxKaGJtUnBJRUVpTENKMWMyVnlibUZ0WlNJNkluSmhibVJwYUhWbllUQTFJaXdpY0dGemMzZHZjbVFpT2lJMk1UTXlOakV4TjJWa05HRTVaR1JtTTJZM05UUmxOekZsTVRFNVpUVmlNeUlzSW5KbFpuSmxjMmhmZEc5clpXNGlPaUpsZVVwb1lrZGphVTlwU2tsVmVra3hUbWxKYzBsdVVqVmpRMGsyU1cifSwidXNlcm5hbWUiOiJyYW5kaWh1Z2EwNSIsImlhdCI6MTY3MDY4MzQ5MywiZXhwIjoxNjcwNjgzNTEzfQ.8FAiy_duyZSAz48vdSnnB9tlhl1jaZUwGlZfqvZ_qe8

###
POST http://localhost:5000/users/login
Content-Type: application/json

{
    "username":"randihuga05",
    "password":"blocked"
}
###
GET http://localhost:5000/users/token